variables:
  FLATPAK_MODULE: pika-backup
  MANIFEST_PATH: build-aux/org.gnome.World.PikaBackup.Devel.json

test:
  image: quay.io/gnome_infrastructure/gnome-runtime-images:x86_64-gnome-44
  tags:
    - flatpak
  interruptible: true
  script:
    - flatpak-builder --user --disable-rofiles-fuse --keep-build-dirs --stop-at=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH}
    - flatpak build-finish --socket=x11 --share=network flatpak_app
    - >
      xvfb-run -a -s "-screen 0 1024x768x24"
      flatpak-builder --user --disable-rofiles-fuse --build-shell=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH} <<END

      LANG=C.UTF-8
      NO_AT_BRIDGE=1
      dbus-run-session
      meson test --no-stdsplit --print-errorlogs

cargo-audit:
  interruptible: true
  allow_failure: true
  image: rust
  script:
    - cargo install cargo-deny
    - cargo deny check

cargo-clippy:
  extends: test
  tags:
    - flatpak
  script:
    - flatpak-builder --user --disable-rofiles-fuse --keep-build-dirs --stop-at=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH}
    - flatpak build-finish --share=network flatpak_app
    - echo "cargo clippy -- -D warnings" | flatpak-builder --user --disable-rofiles-fuse --build-shell=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH}

cargo-fmt:
  interruptible: true
  image: rust:slim
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --color=always --check

pages:
  image: quay.io/gnome_infrastructure/gnome-runtime-images:gnome-master
  tags:
    - flatpak
  interruptible: true
  script:
    - flatpak-builder --user --disable-rofiles-fuse --keep-build-dirs --stop-at=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH}
    - flatpak build-finish --socket=x11 --share=network flatpak_app
    - >
      flatpak-builder --user --disable-rofiles-fuse --build-shell=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH} <<END
        ninja src/doc

      END
    - mkdir public
    - cp -r .flatpak-builder/build/${FLATPAK_MODULE}/_flatpak_build/src/doc public/code-doc
    - chmod -R a=rwx public
  artifacts:
    paths:
      - 'public'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

