test:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/rust_bundle:40
  interruptible: true
  tags:
    - flatpak
  variables:
    FLATPAK_MODULE: pika-backup
    MANIFEST_PATH: build-aux/org.gnome.World.PikaBackup.Devel.json
  script:
    - flatpak-builder --user --disable-rofiles-fuse --keep-build-dirs --stop-at=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH}
    - flatpak build-finish --socket=x11 --share=network flatpak_app
    - >
      xvfb-run -a -s "-screen 0 1024x768x24"
      flatpak-builder --user --disable-rofiles-fuse --build-shell=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH} <<END

      LANG=C.UTF-8
      NO_AT_BRIDGE=1
      dbus-run-session
      meson test --no-stdsplit --print-errorlogs

cargo-audit:
  interruptible: true
  image: rust
  script:
    - cargo install cargo-audit
    - cargo audit

cargo-clippy:
  extends: test
  script:
    - flatpak-builder --user --disable-rofiles-fuse --keep-build-dirs --stop-at=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH}
    - flatpak build-finish --share=network flatpak_app
    - flatpak-builder --user --disable-rofiles-fuse --build-shell=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH} "cargo clippy"

cargo-fmt:
  interruptible: true
  image: rust:slim
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --color=always --check

pages:
  interruptible: true
  script:
    - dnf install -y glib2-devel gtk3-devel libhandy-devel gobject-introspection-devel cairo-devel
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source "$HOME/.cargo/env"
    - cargo doc --no-deps --document-private-items
    - mkdir public
    - cp -r target/doc public/code-doc
  artifacts:
    paths:
      - 'public'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

