cache:
  key: ${CI_JOB_NAME}
  paths:
    - target/

before_script:
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustup update stable
  - rustup component add rustfmt
  - rustup component add clippy
  - cargo install cargo-audit
  - rustc --version && cargo --version

build:
  stage: build
  script:
   - cargo build

code_check:
  stage: test
  script:
   - cargo fmt -- --check
   - cargo clippy
   - cargo audit --deny-warnings

test:
  stage: test
  script:
   - cargo test
   - cargo test -- --ignored

release:
  stage: deploy
  only:
   - tags
  script:
   - cargo build --release
   - cp ./target/release/pika-pile ./
  artifacts:
   paths:
    - pika-pile
