include:
  - project: "GNOME/citemplates"
    file: "flatpak/flatpak_ci_initiative.yml"

variables:
  BUNDLE: "org.gnome.World.PikaBackup.Devel.flatpak"
  APP_ID: "org.gnome.World.PikaBackup.Devel"
  FLATPAK_MODULE: "pika-backup"
  MANIFEST_PATH: "build-aux/org.gnome.World.PikaBackup.Devel.json"
  RUNTIME_IMAGE: "quay.io/gnome_infrastructure/gnome-runtime-images:gnome-master"

cargo-audit:
  image: rust
  interruptible: true
  allow_failure: true
  script:
    - cargo install cargo-deny
    - cargo deny check

cargo-clippy:
  extends: flatpak
  interruptible: true
  tags:
    - flatpak
  script:
    - flatpak-builder --user --disable-rofiles-fuse --keep-build-dirs --stop-at=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH}
    - flatpak build-finish --share=network flatpak_app
    - echo "cargo clippy -- -D warnings" | flatpak-builder --user --disable-rofiles-fuse --build-shell=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH}

cargo-fmt:
  image: rust
  interruptible: true
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --color=always --check

cargo-test:
  image: "${RUNTIME_IMAGE}"
  tags:
    - flatpak
  interruptible: true
  script:
    - flatpak-builder --user --disable-rofiles-fuse --keep-build-dirs --stop-at=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH}
    - flatpak build-finish --socket=x11 --share=network flatpak_app
    - >
      xvfb-run -a -s "-screen 0 1024x768x24"
      flatpak-builder --user --disable-rofiles-fuse --build-shell=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH} <<END

      LANG=C.UTF-8
      NO_AT_BRIDGE=1
      dbus-run-session
      meson test --no-stdsplit --print-errorlogs

flatpak:
  extends: ".flatpak@x86_64"
  variables:
    RUN_TESTS: "0"

flatpak@aarch64:
  extends: ".flatpak@aarch64"
  variables:
    RUN_TESTS: "0"

pages:
  image: "${RUNTIME_IMAGE}"
  stage: deploy
  script:
    - flatpak-builder --user --disable-rofiles-fuse --keep-build-dirs --stop-at=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH}
    - flatpak build-finish --socket=x11 --share=network flatpak_app
    - echo "../build-aux/build-pages-html.bash" | flatpak-builder --user --disable-rofiles-fuse --build-shell=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH}
    - mkdir public
    - cp -r .flatpak-builder/build/${FLATPAK_MODULE}/_flatpak_build/src/doc public/code-doc
    - cp -r .flatpak-builder/build/${FLATPAK_MODULE}/_flatpak_build/help-out public/help
    - cp help/LINGUAS public/help/
    - chmod -R a=rwx public
  artifacts:
    paths:
      - "public"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH