include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

flatpak:
    image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/rust_bundle:3.36'
    variables:
        MANIFEST_PATH: "build-aux/org.gnome.gitlab.sophie_h.PikaPileBackup.yml"
        MESON_ARGS: "-Dprofile=Devel"
        FLATPAK_MODULE: "pika-pile"
        APP_ID: "org.gnome.gitlab.sophie_h.PikaPileBackup"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        BUNDLE: "pika-pile-backup-dev.flatpak"
    extends: .flatpak

nightly:
  extends: '.publish_nightly'
  dependencies: ['flatpak']
