[package]
name = "pika-backup"
description = "Simple backups based on borg"
version = "0.2.2"
authors = ["Sophie Herold <sophie@hemio.de>"]
homepage = "https://wiki.gnome.org/Apps/PikaBackup"
repository = "https://gitlab.gnome.org/World/pika-backup"
edition = "2018"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
chrono-humanize = "0.1"
ctrlc = { version = "3.1", features = ["termination"] }
dbus = "0.9"
gettext-rs = { version = "0.5", features = ["gettext-system"] }
nix = "0.19"
secret-service = "1.1"
shell-words = "1.0"
walkdir = "2.3"
zxcvbn = "2.0"

# data types and handling
arc-swap = "1.0"
enclose = "1.1"
once_cell = "1.3"
quick-error = "2.0"
zeroize = "1.1"

# logging
log = "0.4"
pretty_env_logger = "0.4"
syslog = "5.0"

# serde
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

# GNOME
gdk = "0.13"
gdk-pixbuf = "0.9"
gio = { version = "0.9", features = ["v2_52"] }
glib = "0.10"
gtk = { version = "0.9", features = ["v3_24"] }
pango = "0.9"
libhandy = "0.7"

[dev-dependencies]
matches = "0.1"
