[package]
name = "pika-backup"
description = "Keep your data safe"
version = "0.5.2"
authors = ["Sophie Herold <sophie@hemio.de>"]
homepage = "https://apps.gnome.org/app/org.gnome.World.PikaBackup/"
repository = "https://gitlab.gnome.org/World/pika-backup"
edition = "2021"
default-run = "pika-backup"
rust-version = "1.63"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
async-std = { version = "1.10", features = ["attributes", "unstable"] }
async-trait = "0.1"
chrono = { version = "= 0.4.21", features = ["serde"] }
chronoutil = "0.2"
const-str = "0.5"
default-env = "0.1"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
nix = "0.26"
num-format = "0.4"
regex = { package = "fancy-regex", version = "0.11" }
shell-words = "1.0"
scopeguard = "1.1"
tempfile = "3.2"
walkdir = "2.3"
zxcvbn = "2.0"

# data types and handling
arc-swap = "1.0"
enclose = "1.1"
itertools = "0.10"
once_cell = "1.3"
quick-error = "2.0"
zeroize = "1.1"

# serde
serde = "1.0"
serde_derive = "1.0"
serde_ini = "0.2"
serde_json = "1.0"

# GNOME
adw = { package = "libadwaita", version = "0.3", features = ["v1_3"] }
glib = { version = "*" }
gio = { version = "*"}
gtk = { package = "gtk4", version = "0.6", features = ["v4_8"] }

ashpd = "0.4.0-alpha.4"
gvdb-macros = "0.1"
oo7 = "0.1.0-beta.2"
zbus = "3.1"

[dev-dependencies]
matches = "0.1"
cmd_lib = "1.3"
tmp_env = "0.1"