[package]
name = "pika-backup"
description = "Simple backups based on borg"
version = "0.3.0-alpha"
authors = ["Sophie Herold <sophie@hemio.de>"]
homepage = "https://wiki.gnome.org/Apps/PikaBackup"
repository = "https://gitlab.gnome.org/World/pika-backup"
edition = "2018"
default-run = "pika-backup"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
async-process = "1.0"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3.12"
gettext-rs = { version = "0.6", features = ["gettext-system"] }
nix = "0.20"
num-format = "0.4"
regex = "1.4"
shell-words = "1.0"
tempfile = "3.2"
url = "2.2"
walkdir = "2.3"
zxcvbn = "2.0"

# data types and handling
arc-swap = "1.0"
enclose = "1.1"
itertools = "0.10"
once_cell = "1.3"
quick-error = "2.0"
zeroize = "1.1"

# serde
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

# GNOME
gdk = { version = "*", git = "https://github.com/gtk-rs/gtk-rs.git" }
gdk-pixbuf = { version = "*", git = "https://github.com/gtk-rs/gtk-rs.git" }
gio = { version = "*", features = ["v2_54"], git = "https://github.com/gtk-rs/gtk-rs.git" }
gio-sys = { version = "*", git = "https://github.com/gtk-rs/gtk-rs.git" }
glib = { version = "*", git = "https://github.com/gtk-rs/gtk-rs.git" }
gtk = { git = "https://github.com/gtk-rs/gtk-rs.git", version = "*", features = ["v3_24"] }
pango = { version = "*", git = "https://github.com/gtk-rs/gtk-rs.git" }

ashpd = "0.1"
libhandy = { version = "0.14", git = "https://gitlab.gnome.org/sophie-h/libhandy-rs.git", branch = "gtk-rs-0.14" }
secret-service = "2.0"
zbus = "1.8"

[dev-dependencies]
matches = "0.1"
