[package]
name = "pika-backup"
description = "Simple backups based on borg"
version = "0.4.0-beta.1"
authors = ["Sophie Herold <sophie@hemio.de>"]
homepage = "https://apps.gnome.org/app/org.gnome.World.PikaBackup/"
repository = "https://gitlab.gnome.org/World/pika-backup"
edition = "2021"
default-run = "pika-backup"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
async-std = { version = "1.10", features = ["attributes", "unstable"] }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
chronoutil = "0.2"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
nix = "0.23"
num-format = "0.4"
regex = "1.4"
shell-words = "1.0"
scopeguard = "1.1"
tempfile = "3.2"
walkdir = "2.3"
zxcvbn = "2.0"

# data types and handling
arc-swap = "1.0"
enclose = "1.1"
itertools = "0.10"
once_cell = "1.3"
quick-error = "2.0"
zeroize = "1.1"

# serde
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

# GNOME
adw = { version = "0.1", package = "libadwaita" }
glib = "*"
gio = "*"
gtk = { package = "gtk4", version = "0.4", features = ["v4_6"] }
libsecret = "0.1"

ashpd = "0.3"
zbus = "2.0"

[dev-dependencies]
matches = "0.1"
