[package]
name = "pika-backup"
description = "Simple backups based on borg"
version = "0.1.0"
authors = ["Sophie Herold <sophie@hemio.de>"]
homepage = "https://gitlab.gnome.org/sophie-h/pika-backup"
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
chrono-humanize = "0.0.11"
ctrlc = { version = "3.1", features = ["termination"] }
dbus = "0.8"
gettext-rs = { version = "0.4", features = ["gettext-system"] }
humansize = "1.1"
matches = "0.1"
nix = "0.18"
secret-service = "1.1"
walkdir = "2.3"
zxcvbn = "2.0"

# data types and handling
arc-swap = "0.4"
crossbeam-channel = "0.4"
enclose = "1.1"
once_cell = "1.3"
quick-error = "2.0"
zeroize = "1.1"

# logging
log = "0.4"
pretty_env_logger = "0.4"
syslog = "5.0"

# serde
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

# GNOME
gdk = "0.13"
gdk-pixbuf = "0.9"
gio = { version = "0.9", features = ["v2_52"] }
glib = "0.10"
gtk = { version = "0.9", features = ["v3_24"] }
pango = "0.9"

