[package]
name = "pika-backup"
description = "Simple backups based on borg"
version = "0.3.0-alpha"
authors = ["Sophie Herold <sophie@hemio.de>"]
homepage = "https://wiki.gnome.org/Apps/PikaBackup"
repository = "https://gitlab.gnome.org/World/pika-backup"
edition = "2018"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
chrono-humanize = "0.1"
gettext-rs = { version = "0.5", features = ["gettext-system"] }
nix = "0.19"
shell-words = "1.0"
walkdir = "2.3"
zxcvbn = "2.0"
async-trait = "0.1"
futures = "0.3.12"

# data types and handling
arc-swap = "1.0"
enclose = "1.1"
once_cell = "1.3"
quick-error = "2.0"
zeroize = "1.1"

# serde
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

# GNOME
gtk = { git = "https://github.com/gtk-rs/gtk4-rs.git", package = "gtk4" }
gio = { git = "https://github.com/gtk-rs/gtk-rs.git", features = ["v2_52"] }
libhandy = { git = "https://gitlab.gnome.org/bilelmoussaoui/libadwaita-rs.git", package = "libadwaita" }
secret-service = "2.0"
zbus = "1.8"

[dev-dependencies]
matches = "0.1"
