[package]
name = "pika-backup"
description = "Keep your data safe"
version = "0.5.0-beta.2"
authors = ["Sophie Herold <sophie@hemio.de>"]
homepage = "https://apps.gnome.org/app/org.gnome.World.PikaBackup/"
repository = "https://gitlab.gnome.org/World/pika-backup"
edition = "2021"
default-run = "pika-backup"
rust-version = "1.63"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
async-std = { version = "1.10", features = ["attributes", "unstable"] }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
chronoutil = "0.2"
const-str = "0.4"
default-env = "0.1"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
nix = "0.25"
num-format = "0.4"
regex = { package = "fancy-regex", version = "0.10" }
shell-words = "1.0"
scopeguard = "1.1"
tempfile = "3.2"
walkdir = "2.3"
zxcvbn = "2.0"

# data types and handling
arc-swap = "1.0"
enclose = "1.1"
itertools = "0.10"
once_cell = "1.3"
quick-error = "2.0"
zeroize = "1.1"

# serde
serde = "1.0"
serde_derive = "1.0"
serde_ini = "0.2"
serde_json = "1.0"

# GNOME
adw = { package = "libadwaita", version = "0.2", git = "https://gitlab.gnome.org/World/Rust/libadwaita-rs.git", features = ["v1_2"] }
glib = { version = "*", git = "https://github.com/gtk-rs/gtk-rs-core" }
gio = { version = "*", git = "https://github.com/gtk-rs/gtk-rs-core" }
gtk = { package = "gtk4", version = "0.5", features = ["v4_8"], git = "https://github.com/gtk-rs/gtk4-rs" }

ashpd = "0.3"
gvdb-macros = "0.1"
oo7 = { version = "0.1.0-alpha.5", git = "https://github.com/sophie-h/oo7.git", branch = "fork" }
zbus = "3.1"

[dev-dependencies]
matches = "0.1"
cmd_lib = "1.3"
tmp_env = "0.1"